### ISSUE TITLE
Error during sided_setup phase with latest version of Forge

### ISSUE THREAD

**Issue by Gamemassa** [juancarloscp52/spyglass-improvements#10]
MC version: 1.19
Forge version: 41.0.85
Mod version: 1.3

I loaded up a Minecraft with Spyglass Improvements and got an "error during the sided_setup phase". I've attached the crash report here.

[crash-2022-07-09_19.28.25-fml.txt](https://github.com/juancarloscp52/spyglass-improvements/files/9078070/crash-2022-07-09_19.28.25-fml.txt)

**Comment by Baggytrousers27** [comment]
Forges 41.0.64 and 41.0.94+ have breaking changes.

Loading with 41.0.94 and spyglass_improvements-1.3+mc1.19+forge gets this error:
java.lang.NoClassDefFoundError: net/minecraftforge/client/ClientRegistry

[crashlog](https://github.com/juancarloscp52/spyglass-improvements/files/9126984/crash-2022-07-17_13.08.24-fml.txt)

**Comment by juancarloscp52** [comment]
fixed with commit 71ac6c84628e0a662b12453112187f450972ac96
Thanks for reporting the issue!
