### ISSUE TITLE
Allow rebinding quick access key [Feature request]

### ISSUE THREAD

**Issue by lemorage** [juancarloscp52/spyglass-improvements#27]
Is it possible to rebind the quick access key for this mod when multiple key bindings conflict? Currently, the default key for quick access is 'Z', but I didn't see any choice to be able to change it to another key.

> Additional Information:
> - Mod version: 1.20 Forge
> - Minecraft version: 1.20.1

**Comment by juancarloscp52** [comment]
Hello! you should be able to change the quick access keybind in the minecraft controls settings. It is usually at the botton of the list.

**Comment by lemorage** [comment]
> Hello! you should be able to change the quick access keybind in the minecraft controls settings. It is usually at the botton of the list.

Ohh, my bad! I never noticed that. Thanks for mentioning and the good mod.
