### ISSUE TITLE
Bug with Nyf's Quivers

### ISSUE THREAD

**Issue by raffle2** [juancarloscp52/spyglass-improvements#28]
Hey there, thanks for the mod c:
Found a lil bug when using this with https://www.curseforge.com/minecraft/mc-mods/nyfs-quivers/
If you have a quiver equipped in your back, when you zoom in with your spyglass, the 3D model of the quiver appears on the center of the screen, only while using the spyglass.

**Comment by juancarloscp52** [comment]
seems to be working with latest versions of quivers and spyglass, please reopen if the issue appears again
