### ISSUE TITLE
Incompatibility with visual overhaul

### ISSUE THREAD

**Issue by ItsProfessional** [juancarloscp52/spyglass-improvements#29]
Visual overhaul adds icons to menu buttons. When going to spyglass improvements' settings in the settings screen, the game crashes.

**Comment by SettingDust** [comment]
may relate https://github.com/juancarloscp52/spyglass-improvements/issues/24
I have Visual overhaul

**Comment by zoqin** [comment]
I have visual overhaul too and the mod crash on 1.20.1

**Comment by juancarloscp52** [comment]
Closing as fixed by visual overhaul 5.1.0
