### ISSUE TITLE
Feature Request: Curios and Trinkets support

### ISSUE THREAD

**Issue by Raidobw2** [juancarloscp52/spyglass-improvements#3]
Hi! My suggestion is about a Curios/Trinket slot for the spyglass, where it can be pulled from and returned to after use
For Forge: https://www.curseforge.com/minecraft/mc-mods/curios
For Fabric: https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric
Have a nice day

**Comment by sternschnaube** [comment]
This sounds really great - I'm up for this idea 🥳

**Comment by xR4YM0ND** [comment]
@juancarloscp52 you may consider this for the next update?

**Comment by juancarloscp52** [comment]
Hello! curios was added last February to the forge versions and I've just updated most fabric versions to work with trinkets!
https://modrinth.com/mod/spyglass-improvements/versions?l=fabric
