### ISSUE TITLE
PLEASE add a config option to disable putting the spyglass in your hand when using the shortcut key

### ISSUE THREAD

**Issue by leftbones** [juancarloscp52/spyglass-improvements#32]
Title says it all, it's *super* annoying to me that using the shortcut key takes the shield/torches/etc out of my offhand. I don't really ever want the spyglass in my hand, I just want to be able to use it quickly from my inventory.

Thank you!

**Comment by juancarloscp52** [comment]
For now, please use curios/trinkets and place the spyglass in the trinket slot for this functionality.
