### ISSUE TITLE
[BUG] 'AutoRefill' of InventoryProfilesNext mod breaks somthing in SpyglassImprovements mod.

### ISSUE THREAD

**Issue by gezinfly** [juancarloscp52/spyglass-improvements#34]
Please see the details in:
https://github.com/blackd/Inventory-Profiles/issues/371#issue-2054875040

It's a compatibility problem. I should ask both sides.
The issue in the other side is more complex so that I wrote it previously. It is for sure that the details will be detailed.

**Comment by kimchiloof** [comment]
This was mentioned in #7. I had a look at InventoryProfilesNext's code and couldn't really figure out how to add the blacklist automatically. 

If there's a way to access their config via code that could be solved on either side but the simplest is a manual blacklist of "minecraft:spyglass". 

Maybe juancarloscp52 can add an FAQ to the mod listing page to say to manually add the blacklist? (and this issue can be marked closed/duplicate/wontfix)

**Comment by gezinfly** [comment]
I'm sorry for my neglect. The issue can be closed.

Maybe it IS necessary to add an FAQ. 

~But it is strange that the problem even remains after putting "minecraft:spyglass" into blacklist manually.~ Please don't forget to ask them to "reload rule files" as well. _I forgot it so it didn't work. How Silly I Was！\*Laugh\*_
