### ISSUE TITLE
[Suggestion:] Compatability with Trinkets

### ISSUE THREAD

**Issue by ElRokur** [juancarloscp52/spyglass-improvements#42]
Love the mod, love the curious compat. Would it be possiible to add compat for trinkets for fabric?
https://www.curseforge.com/minecraft/mc-mods/trinkets

**Comment by juancarloscp52** [comment]
Hello! trinkets support was just added for the latest Spyglass-Improvements 1.5 on fabric for minecraft 1.18.2 to 1.20.4
https://modrinth.com/mod/spyglass-improvements/versions?l=fabric
