### ISSUE TITLE
Move away from cancelling `MouseHandler.turnPlayer` for better intermod compatibility

### ISSUE THREAD

**Issue by SplendidAlakey** [juancarloscp52/spyglass-improvements#44]
Recently I had an issue with the mod not entirely working together with [Shoulder Surfing Reloaded](https://modrinth.com/mod/shoulder-surfing-reloaded), the spyglass would render as a solid glass texture. That issue has now been fixed, as you can see here: https://github.com/Exopandora/ShoulderSurfing/issues/165.

However, in the process of fixing the aforementioned bug, the author of Shoulder Surfing Reloaded noted that due to Spyglass Improvements completely cancelling `MouseHandler.turnPlayer` you can't move your mouse while looking through the spyglass in third person. They also suggested a couple of potential solutions which you can see here: https://github.com/Exopandora/ShoulderSurfing/issues/165#issuecomment-2027833131.

**Comment by SplendidAlakey** [comment]
The issue was resolved on their side https://github.com/Exopandora/ShoulderSurfing/issues/165#issuecomment-2041503257, but I'll keep this open in case you'd still like to implement the change.

**Comment by juancarloscp52** [comment]
Closed as fixed in 1.5.3
