### ISSUE TITLE
Incompatibility with Camera Utils

### ISSUE THREAD

**Issue by xXTravioXx** [juancarloscp52/spyglass-improvements#45]
Hello Juan Carlos cp52,

It appears that camera utils is dominating this mods use of the scroll wheel. I dug in the class files for both mods for an hour but it appears all the scroll bind methods are labeled by class and method numbers and I really didn't want to search for the needle in the haystack, so figured I'd reach and see if there may be an easier way to fix it. 

I realize compatibility issues aren't necessarily this mods problem but I figured I'd ask to see if your interested in it, if not I may attempt to learn some more java and try to crudely solve the issue.

Thank you for your great mod! Sincerely Travio.

**Comment by juancarloscp52** [comment]
Hello! I've released a new version of spyglass improvements that improves compatibility with other mods. For camera utils to work a change needs to be made in this mod that I've recommended in this pull request https://github.com/henkelmax/camera-utils/pull/73, once they approve it both mods will be able to work together.

**Comment by juancarloscp52** [comment]
Fixed with latest spyglass improvements version and camera utils 1.21.1-1.0.15
