### ISSUE TITLE
Hotkey doesn't work in creative mode on a 1.20.4 server, functions normally in survival, and was working in version 1.4 (Fabric). 

### ISSUE THREAD

**Issue by ErakAcheron** [juancarloscp52/spyglass-improvements#46]
As described in the title, the spyglass zoom sound plays but zoom itself doesn't happen, regardless of whether or not I have a spyglass in my inventory, however if I holding the spyglass item and press the hotkey it will still zoom. Works fine in survival. 

I've tried changing the keybind and checking the logs for keybind errors, but have failed to find the cause. 

I do wonder if it could be an aspect of the new 1.5 trinkets integration? On the creative server I have operator status but the server doesn't have trinkets installed, perhaps there's some issue there? 

Not a high priority issue to be fair, just a weird bug.

**Comment by juancarloscp52** [comment]
Hello! I think i have solved the issue with the latest version (1.5.1). When playing on servers spyglass improvements is no longer necessary unless you want to use trinkets, in which you'll need to have them installed on both client and server.
Thank you for opening the issue!

**Comment by ErakAcheron** [comment]
Apologies for being a late, but yes I can confirm that the issue is now fixed on my end as well! 

Thank you!
