### ISSUE TITLE
[1.20.1] Incompatible with latest version of Curios

### ISSUE THREAD

**Issue by emihead** [juancarloscp52/spyglass-improvements#59]
Hey, I'm not sure if the 1.20.1 version is still being supported but it's claiming to be incompatible with versions of Curios after 6.0. I'm not sure if there is an actual issue or if an arbitrary limit was just put on the version compat.

**Comment by juancarloscp52** [comment]
Hi! The only versions of Curios compatible with MC 1.20.1 are 5.x versions. ([see this](https://www.curseforge.com/minecraft/mc-mods/curios/files/all?page=1&pageSize=50&version=1.20.1)). Version 6.0 are for MC 1.20.2

**Comment by emihead** [comment]
Oh that's odd, maybe an issue with the launcher I was using? Thanks for letting me know!
