### ISSUE TITLE
spyglass doesnt go back to inventory

### ISSUE THREAD

**Issue by vos6434** [juancarloscp52/spyglass-improvements#7]
Spyglass stays in offhand when the offhand is empty. It should go back to inventory just how it behaves when the offhand is occupied.

**Comment by juancarloscp52** [comment]
Hi! Im unable to reproduce this issue. What version are you using, forge or fabirc? Are you using any mods/modpack? Which one?

**Comment by vos6434** [comment]
I'm on Fabric and Inventory Profiles Next seems to be causing the issue.

**Comment by vos6434** [comment]
Disabling or blacklisting spyglass from auto refill in Inventory Profiles Next fixes this.
