### ISSUE TITLE
[Feature Request] Disallow use of the keybind when a spyglass is not present in the inventory

### ISSUE THREAD

**Issue by foul-fortune-feline** [juancarloscp52/spyglass-improvements#9]
Pretty self explanatory

**Comment by juancarloscp52** [comment]
Hi! this already exist in spyglass-improvements. When in survival mode, you have to have a spyglass in the inventory for the keybind to work. If you are in creative mode, this restriction does not apply.

**Comment by foul-fortune-feline** [comment]
Huh. I swore I was able to do it in survival without having one -w-'
Maybe I'm misremembering, if not I'll send u a bug report

Alos thnx for the prompt response~
